###
POST http://127.0.0.1:8080/user/login
Content-Type: application/json

{
  "userName": "zhangsan",
  "password": "123"
}

###
GET http://127.0.0.1:8080/goods/select
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaXNzIjoiRGFya2lyaXMiLCJleHAiOjE3MzYxNzM1MzR9.Ts3npOPXx21WtalEW8GUN91FpIIvHq7iniyKlTxvbKc2GISrqnyQHIwmWnfjHdWOwHpSFHwpsRZbcxGu7iU4Cg


###
GET http://127.0.0.1:8080/goods/getGoods
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaXNzIjoiRGFya2lyaXMiLCJleHAiOjE3MzYxNzM1MzR9.Ts3npOPXx21WtalEW8GUN91FpIIvHq7iniyKlTxvbKc2GISrqnyQHIwmWnfjHdWOwHpSFHwpsRZbcxGu7iU4Cg

###
POST http://127.0.0.1:8080/goods/addGoods
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwiaXNzIjoiRGFya2lyaXMiLCJleHAiOjE3MzYxNzM3NDd9.AdRIb5kdp5Derh6sEnNrD0i3Bu0bnmBkhDzoZG8Yero_lV1nhmVLYkybuenjKlH8ppEaU1FiN9xkrcgxSDJYbg

